"""
ⒸAngelaMos | 2026
llm/generator.py
"""
from __future__ import annotations

import re
from datetime import datetime
from dataclasses import dataclass

from typing import TYPE_CHECKING

from codeworm.core import get_logger
from codeworm.llm.client import (
    OllamaClient, 
    OllamaError,
)
from codeworm.llm.prompts import (
    PromptBuilder,
    build_commit_prompt, 
    build_documentation_prompt,
)
if TYPE_CHECKING:
    from codeworm.analysis import AnalysisCandidate
    from codeworm.core.config import OllamaSettings

logger = get_logger("generator")


@dataclass
class GeneratedDocumentation:
    """
    Generated documentation for a code snippet
    """
    content: str
    commit_message: str
    snippet_filename: str
    generated_at: datetime
    tokens_used: int
    generation_time_ms: int

    @property
    def word_count(self) -> int:
        return len(self.content.split())

    def to_markdown(self, candidate: AnalysisCandidate) -> str:
        """
        Format as markdown file content
        """
        header = f"""# {candidate.snippet.display_name}

**Repository:** {candidate.snippet.repo}
**File:** {candidate.scanned_file.relative_path}
**Language:** {candidate.snippet.language.value}
**Lines:** {candidate.snippet.start_line}-{candidate.snippet.end_line}
**Complexity:** {candidate.snippet.complexity}

---

"""
        code_block = f"""## Source Code

```{candidate.snippet.language.value}
{candidate.snippet.source}
```

---

"""
        doc_section = f"""## Documentation

{self.content}

---

*Generated by CodeWorm on {self.generated_at.strftime('%Y-%m-%d %H:%M')}*
"""
        return header + code_block + doc_section


class DocumentationGenerator:
    """
    Generates documentation for code snippets using LLM
    """
    def __init__(self, client: OllamaClient) -> None:
        """
        Initialize generator with Ollama client
        """
        self.client = client
        self.prompt_builder = PromptBuilder()

    async def generate(self, candidate: AnalysisCandidate) -> GeneratedDocumentation:
        """
        Generate documentation for a candidate
        """
        start_time = datetime.now()

        system, user = build_documentation_prompt(candidate)
        doc_result = await self.client.generate_with_retry(user, system)
        documentation = self._clean_documentation(doc_result.text)

        system, user = build_commit_prompt(documentation, candidate)
        commit_result = await self.client.generate(user, system, temperature=0.4)
        commit_message = self._clean_commit_message(commit_result.text)

        generation_time = int((datetime.now() - start_time).total_seconds() * 1000)
        total_tokens = doc_result.total_tokens + commit_result.total_tokens

        filename = self._generate_filename(candidate)

        logger.info(
            "documentation_generated",
            function=candidate.snippet.display_name,
            repo=candidate.snippet.repo,
            tokens=total_tokens,
            time_ms=generation_time,
        )

        return GeneratedDocumentation(
            content=documentation,
            commit_message=commit_message,
            snippet_filename=filename,
            generated_at=datetime.now(),
            tokens_used=total_tokens,
            generation_time_ms=generation_time,
        )

    def _clean_documentation(self, text: str) -> str:
        """
        Clean up generated documentation
        """
        text = text.strip()

        if text.startswith("```"):
            lines = text.split("\n")
            if lines[-1].strip() == "```":
                lines = lines[1:-1]
            else:
                lines = lines[1:]
            text = "\n".join(lines)

        text = re.sub(r"^(Here is|Here's|The following|This is) .+?:\n+", "", text, flags=re.IGNORECASE)

        return text.strip()

    def _clean_commit_message(self, text: str) -> str:
        """
        Clean up generated commit message
        """
        text = text.strip()

        text = text.strip('"\'')

        if "\n" in text:
            text = text.split("\n")[0]

        text = re.sub(r"^(commit message:|message:)\s*", "", text, flags=re.IGNORECASE)

        if len(text) > 72:
            text = text[:69] + "..."

        return text.strip()

    def _generate_filename(self, candidate: AnalysisCandidate) -> str:
        """
        Generate filename for the snippet
        """
        date_str = datetime.now().strftime("%Y-%m-%d")
        name = candidate.snippet.display_name.lower()
        name = re.sub(r"[^a-z0-9]+", "-", name)
        name = name.strip("-")

        if len(name) > 40:
            name = name[:40].rsplit("-", 1)[0]

        return f"{date_str}_{name}.md"


async def generate_documentation(
    candidate: AnalysisCandidate,
    settings: OllamaSettings,
) -> GeneratedDocumentation:
    """
    Convenience function to generate documentation
    """
    from codeworm.llm.client import create_client

    client = await create_client(settings)
    try:
        generator = DocumentationGenerator(client)
        return await generator.generate(candidate)
    finally:
        await client.close()
